// Case types used for guided practice. Each has a scaffold of steps, a default timer and a self-review list.
// `tracker` says where a finished session is logged: [week, trackerId].

export const CASE_TYPES = {
  design: {
    label: 'Product design',
    short: 'Design',
    minutes: 12,
    tracker: [2, 'design'],
    intro: 'Design something new for a user or a problem. Structure beats speed: understand the user before you touch features.',
    steps: [
      { t: 'Clarify', p: 'What are we building, for which goal, on which platform and in which market? Any time or cost limits?', h: 'One or two sharp questions are enough. Say the assumption you are making and ask if it works, instead of firing a list of questions.' },
      { t: 'Users', p: 'List 2–3 personas: who they are, how they behave, what motivates them. Pick one and say why.', h: 'Be specific. "Young urban users" is not a segment. Choose on size of the segment and how badly their need is unmet.' },
      { t: 'Journey', p: 'Walk the chosen persona through the task as it happens today, before your product exists.', h: 'A simple lens: what triggers them, their first steps, the core task, how they finish, what happens after.' },
      { t: 'Pain points', p: 'Pull 3 crisp pain points from the journey. Which one hurts most?', h: 'Rank on how acute and how frequent each one is. Ground them in behaviour, not assumptions.' },
      { t: 'Solutions', p: 'Give 3–4 ideas that solve the top pain point, from the obvious to the bold.', h: 'Start with the simple, practical fix. Bring in AI only where it clearly adds value.' },
      { t: 'Prioritise', p: 'Which idea ships first? Score on impact vs effort (or RICE) and explain.', h: 'The choice should follow from the persona and pain point you picked. Keep the story consistent.' },
      { t: 'Metrics', p: 'One north star, 2–3 feature metrics and one metric that could get worse.', h: 'Specific beats vague: "7-day retention of new users", not "engagement".' },
      { t: 'Summarise', p: 'In 20–30 seconds: who you built for, which problem, what ships first and why.', h: 'A short recap brings the answer full circle and shows you can structure communication.' },
    ],
    rubric: [
      'I did not jump straight to features',
      'I picked one specific user segment and stayed with it',
      'Pain points came from the journey, not from thin air',
      'Every solution maps to the pain point I chose',
      'My prioritisation had a clear reason',
      'My metrics were specific and included a counter metric',
      'I closed with a short recap',
    ],
  },
  improve: {
    label: 'Product improvement',
    short: 'Improve',
    minutes: 12,
    tracker: [2, 'design'],
    intro: 'Improve a product, feature or journey that already exists. Anchor on one goal and one user group.',
    steps: [
      { t: 'Goal and scope', p: 'What does "improve" mean here: engagement, growth, revenue or satisfaction? Which platform, flow or geography?', h: 'If the interviewer leaves it open, pick a goal, say why, and ask for buy-in.' },
      { t: 'Product today', p: 'In two lines: what the product does, for whom, and how it makes money.', h: 'Shows you know the product before you try to change it.' },
      { t: 'Users', p: 'Segment users (for example frequent, occasional, lapsed) and choose one group to focus on.', h: 'Pick where the goal is most at risk or the upside is largest.' },
      { t: 'Journey and pain points', p: 'Walk that group through the key flow and list where it breaks for them.', h: 'Name 3 pain points and pick the most acute and frequent one.' },
      { t: 'Solutions', p: 'Propose 3–4 improvements for that pain point.', h: 'Lay out a short roadmap, then go deep on the one or two worth doing now.' },
      { t: 'Prioritise', p: 'Rank the ideas on impact vs effort and choose what ships first.', h: 'Mention what you are deliberately not doing and why.' },
      { t: 'Metrics', p: 'Product-level metric, feature-level metrics and a negative metric to watch.', h: 'Think about how you would A/B test the change before a full rollout.' },
      { t: 'Summarise', p: 'Recap the key decision and why you made it.', h: 'For example: "I focused on occasional users because retention is most at risk there."' },
    ],
    rubric: [
      'I agreed on what "improve" meant before solving',
      'I focused on one user group',
      'Pain points were tied to a specific flow',
      'I went deep on one or two ideas instead of listing ten',
      'I named metrics, including one that could go down',
      'I summarised my key decision',
    ],
  },
  app: {
    label: 'App analysis and favourite product',
    short: 'App analysis',
    minutes: 10,
    tracker: [1, 'products'],
    intro: 'Break down an app like a PM, or prepare the "favourite product" answer. Critique, don\'t praise.',
    steps: [
      { t: 'Value proposition', p: 'What job does the app do for its users, in one or two lines?', h: 'Ask: what would the user do if this app did not exist?' },
      { t: 'Why this app', p: 'What makes it different from competitors? What is its edge?', h: 'For a favourite product, pick one you have actually thought about, not the obvious choice.' },
      { t: 'Users', p: 'Who uses it? New, regular and power users can have very different needs.', h: 'Consider accessibility too: low vision, low bandwidth, low-end phones.' },
      { t: 'Key journeys', p: 'List the main journeys and walk one end to end.', h: 'Note the friction points and decision points along the way.' },
      { t: 'What to improve', p: 'Name 2–3 improvements and why they matter to users and the business.', h: 'Avoid stopping at looks. Go from how it looks, to how it works, to why it exists.' },
      { t: 'Metrics', p: 'North star plus 3–4 supporting metrics for the app.', h: 'The north star should reflect value delivered to the user.' },
    ],
    rubric: [
      'I stated the core job the app does',
      'I compared it with at least one competitor',
      'I critiqued, not just praised',
      'My improvements were tied to a user and a journey',
      'I gave a north star metric with a reason',
    ],
  },
  rca: {
    label: 'Root cause analysis',
    short: 'RCA',
    minutes: 12,
    tracker: [3, 'rca'],
    intro: 'A metric moved. Narrow down to the real cause step by step before suggesting any fix.',
    steps: [
      { t: 'Define the metric', p: 'Restate the metric in your own words. How is it calculated? Has its definition changed?', h: 'Get the interviewer to confirm what the metric means before going further.' },
      { t: 'Scope the drop', p: 'Since when, by how much, sudden or gradual? Which platform, geography, user segment?', h: 'Sudden drops usually point to a release, bug or outage. Gradual ones point to behaviour or market shifts.' },
      { t: 'Check the data', p: 'Could this be a tracking, logging or reporting problem?', h: 'Data issues are common and often forgotten. Rule them out first.' },
      { t: 'External factors', p: 'Competitors, seasonality, regulation, bad press, macro events?', h: 'Ask: is this industry-wide or only us?' },
      { t: 'Internal factors', p: 'Recent releases, UI changes, bugs, pricing, promotions, policy or ops changes?', h: 'Also check cannibalisation by one of our own new features or products.' },
      { t: 'Walk the funnel', p: 'Map the user journey and find the step where users drop off.', h: 'Input, processing, output: where does it break?' },
      { t: 'Hypotheses', p: 'List likely causes, rank them, and say what data would confirm each.', h: 'Rank by likely impact times ease of validating.' },
      { t: 'Fix and verify', p: 'What would you do about the root cause, and how would you know it worked?', h: 'Internal and fixable: hotfix or release. External: escalate and align stakeholders.' },
    ],
    rubric: [
      'I confirmed what the metric meant',
      'I asked sudden or gradual, and since when',
      'I ruled out data issues early',
      'I segmented before forming hypotheses',
      'I separated internal from external causes',
      'I walked the funnel step by step',
      'I named the data that would confirm my hypothesis',
      'I proposed a fix and how to measure it',
    ],
  },
  metrics: {
    label: 'Metrics and success',
    short: 'Metrics',
    minutes: 10,
    tracker: [3, 'metricq'],
    intro: 'Define how you would measure a product or feature. Tie every metric to a goal.',
    steps: [
      { t: 'Goal and context', p: 'What is the product for, and is the goal growth, engagement or revenue? Who are the users?', h: 'Your primary goal decides your primary metric.' },
      { t: 'Journey', p: 'Outline key user actions from discovery to becoming a loyal user.', h: 'Acquisition, activation, retention, referral, revenue is a handy spine.' },
      { t: 'Metrics per stage', p: 'List candidate metrics for each stage.', h: 'Mix leading indicators (predict success) and lagging ones (confirm it).' },
      { t: 'North star and KPIs', p: 'Commit to one north star and 3–4 KPIs. Justify the choice.', h: 'A good north star reflects user value, matches strategy and leads revenue.' },
      { t: 'Counter metrics', p: 'What could go wrong if you push the main metric? What guardrail would stop a launch?', h: 'Ask: how could someone move this number without helping the user?' },
    ],
    rubric: [
      'I clarified the goal first',
      'I used the user journey to find metrics',
      'I picked one north star and explained why',
      'I avoided vanity metrics',
      'I named a counter metric or guardrail',
    ],
  },
  gtm: {
    label: 'Go-to-market',
    short: 'GTM',
    minutes: 15,
    tracker: [4, 'gtm'],
    intro: 'Plan how a product reaches the right users, at the right time, through the right channels.',
    steps: [
      { t: 'Objective', p: 'What does the product do, where does it sit in the company\'s portfolio, and why launch now?', h: 'Agree on the goal of the launch: acquisition, retention, revenue.' },
      { t: 'Value proposition', p: 'For [target customer] who [need], our product is a [category] that [benefit]. Unlike [alternative], it [differentiator].', h: 'Keep it one sentence the customer would recognise.' },
      { t: 'Target segments', p: 'Primary, secondary and tertiary segments, with why each matters.', h: 'Be concrete about age, location, behaviour and motivation.' },
      { t: 'Market and competition', p: 'Market size, growth and who we compete with. Where is the gap?', h: 'Include substitutes, not only direct competitors.' },
      { t: 'Pricing', p: 'How will we charge, and why? Value, competitor or cost based? Freemium, tiers, subscription?', h: 'Avoid pure cost-plus pricing in a launch case.' },
      { t: 'Channels and marketing', p: 'Where do these customers spend time? Plan awareness, interest, decision and adoption.', h: 'Pick a motion: product-led, sales-led, inbound or demand generation.' },
      { t: 'Launch plan', p: 'Pilot, then scale. What happens before and after launch?', h: 'A phased rollout by city or segment reduces risk.' },
      { t: 'Metrics and risks', p: 'How will you know it worked? What could go wrong?', h: 'Think adoption, retention, CAC. Check risks with a PESTEL lens.' },
    ],
    rubric: [
      'I clarified why the product is launching',
      'I wrote a clear value proposition',
      'I chose specific target segments',
      'I covered pricing and channels',
      'I proposed a phased launch',
      'I defined success metrics and risks',
    ],
  },
  prioritisation: {
    label: 'Prioritisation',
    short: 'Prioritise',
    minutes: 10,
    tracker: [4, 'prio'],
    intro: 'Decide what to build, defer or drop when resources are limited. The reasoning matters more than the framework label.',
    steps: [
      { t: 'Goal and constraints', p: 'What is the company trying to achieve, and what are the limits: team, time, tech?', h: 'Start from the north star. Features that don\'t serve it should be questioned.' },
      { t: 'Options', p: 'List the features, bets or requests on the table.', h: 'Group them by who asked and what problem each solves.' },
      { t: 'Score', p: 'Score each option with a framework that fits: RICE, ICE, value vs effort, MoSCoW or Kano.', h: 'RICE breaks down when comparing very different kinds of bets. Say so if it applies.' },
      { t: 'Decide', p: 'Build, defer or drop each. What ships first?', h: 'Quick wins first, big projects broken into phases, low value high effort avoided.' },
      { t: 'Trade-offs', p: 'What are you giving up? What risks remain, and how will you revisit the call?', h: 'Share the reasoning with stakeholders. It builds trust even when you say no.' },
    ],
    rubric: [
      'I anchored on a goal before scoring',
      'I used a framework without hiding behind it',
      'I made a clear call',
      'I said what I would not do and why',
    ],
  },
  pricing: {
    label: 'Pricing',
    short: 'Pricing',
    minutes: 10,
    tracker: [4, 'pricing'],
    intro: 'Set or change a price. Start from the business goal and the value to the customer.',
    steps: [
      { t: 'Product', p: 'What exactly is being priced, and what can it do?', h: 'Don\'t hesitate to ask. You must be clear on the product first.' },
      { t: 'Business goal', p: 'Market share, profit or user acquisition?', h: 'Lower prices grow share, higher prices grow margin. Respect the brand: premium products shouldn\'t be slashed suddenly.' },
      { t: 'Market stage', p: 'Is the market forming, growing, mature or declining?', h: 'In a forming market price on cost and perceived value. Once leaders exist, benchmark against them.' },
      { t: 'Customer and value', p: 'Which segment gets the most value? What is their next best alternative? What will they pay?', h: 'Translate the product\'s benefit into money saved or earned.' },
      { t: 'Strategy and model', p: 'Cost-plus, competitor-based or value-based? Freemium, tiers, usage-based, per user?', h: 'Most good answers combine all three lenses to land on a number.' },
      { t: 'Risks', p: 'How will customers, competitors and suppliers react? What about churn?', h: 'Model the churn impact, not just the revenue gain from the new price.' },
    ],
    rubric: [
      'I set the business goal first',
      'I considered the customer\'s willingness to pay',
      'I used more than one pricing lens',
      'I landed on a number or range',
      'I checked churn and competitor reaction',
    ],
  },
  guesstimate: {
    label: 'Guesstimate',
    short: 'Guesstimate',
    minutes: 8,
    tracker: [5, 'guess'],
    intro: 'Estimate a number with logic you can defend. The approach matters more than the exact answer.',
    steps: [
      { t: 'Clarify', p: 'What exactly are we estimating: which metric, geography, time period and customer segment?', h: 'Clarifying also buys you thinking time.' },
      { t: 'Approach', p: 'Top-down, bottom-up, supply side or demand side? Outline the steps and check with the interviewer.', h: 'Validating the approach first saves you from solving the wrong problem.' },
      { t: 'Assumptions', p: 'State each assumption and split into segments (age, city, income, usage).', h: 'Tie assumptions to real behaviour and your own experience where you can.' },
      { t: 'Calculate', p: 'Work it through out loud with round numbers.', h: 'Use 350 days instead of 365. Simple maths means fewer slips.' },
      { t: 'Sanity check', p: 'Does the answer make sense? Try a second method or a known benchmark.', h: 'Catching your own error beats having the interviewer catch it.' },
    ],
    rubric: [
      'I clarified scope before calculating',
      'I agreed the approach first',
      'I said every assumption out loud',
      'I used round numbers',
      'I sanity-checked the final number',
    ],
  },
  strategy: {
    label: 'Strategy',
    short: 'Strategy',
    minutes: 12,
    tracker: [4, 'strategy'],
    intro: 'Should a company enter a market, launch a line or change course? Be structured, defensible and honest about trade-offs.',
    steps: [
      { t: 'Current state', p: 'Where is the company today: strengths, assets, users, business model?', h: 'Know the company and how it makes money.' },
      { t: 'Goal', p: 'What is the company trying to achieve with this move?', h: 'Revenue, retention, a data moat, defending share?' },
      { t: 'Options', p: 'What are the ways to do it: build, buy, partner? Enter or not?', h: 'Check market size, competition and whether the company can execute.' },
      { t: 'Trade-offs and risks', p: 'Regulatory, market, operational, brand risks. What do we give up?', h: 'A good answer does not need to be right. It needs to be structured and defensible.' },
      { t: 'Recommendation', p: 'Make the call and give a phased plan.', h: 'Short, mid and long term steps make it concrete.' },
    ],
    rubric: [
      'I described the company\'s current position',
      'I laid out more than one option',
      'I weighed risks honestly',
      'I made a clear recommendation',
    ],
  },
  moonshot: {
    label: 'Moonshot',
    short: 'Moonshot',
    minutes: 15,
    tracker: [2, 'design'],
    intro: 'Solve a massive problem with technology in a fundamentally new way. Tests vision, empathy and first-principles thinking.',
    steps: [
      { t: 'Vision', p: 'What does the world look like if this problem is solved?', h: 'Frame the fundamental problem, not a feature ("build a platform for X" is not a vision).' },
      { t: 'Users', p: 'Who are the primary and secondary users? Who do you start with?', h: 'You don\'t launch for everyone. Pick a group with high need and willingness to try.' },
      { t: 'Core problem', p: 'What is the root pain that causes the big problem?', h: 'Go to first principles.' },
      { t: 'Transform', p: 'How does technology change the game here?', h: 'Be ambitious, but avoid irrational tech justified by "the future".' },
      { t: 'Adoption', p: 'MVP, then versions that scale. What does each phase prove?', h: 'Prove the concept small first, then expand.' },
      { t: 'Metrics', p: 'How will you know it\'s working at each phase?', h: 'Early metrics prove the concept; later ones prove scale.' },
    ],
    rubric: [
      'I stated a clear vision',
      'I picked a starting user group',
      'I found the core problem',
      'I had a phased adoption plan',
    ],
  },
  behavioural: {
    label: 'Behavioural',
    short: 'Behavioural',
    minutes: 3,
    tracker: [5, 'behav'],
    intro: 'Tell a real story in 2–3 minutes. Tell it, don\'t recite it.',
    steps: [
      { t: 'Situation', p: 'Set the scene briefly. Skip details that don\'t matter.', h: 'Enough context for the interviewer to picture it.' },
      { t: 'Task', p: 'What were you responsible for, and what made it hard?', h: 'Or name the obstacles if there were several.' },
      { t: 'Action', p: 'What did you do? What decision did you make and what trade-off did it involve?', h: 'Say "I", not "we". Stick to what you actually did.' },
      { t: 'Result', p: 'What happened? Put a number on it if you can.', h: '"We cut processing time by 30%" beats "it went well".' },
      { t: 'Reflection', p: 'What would you do differently? What did you learn?', h: 'Most candidates skip this. It shows you learn, not just narrate.' },
    ],
    rubric: [
      'My action was specific and mine',
      'I mentioned a decision or trade-off',
      'My result was measurable',
      'I added a reflection',
      'It fit in about 2–3 minutes',
    ],
  },
}

export const TYPE_ORDER = ['design', 'improve', 'app', 'rca', 'metrics', 'gtm', 'prioritisation', 'pricing', 'strategy', 'moonshot', 'guesstimate', 'behavioural']
