// Company primers. Questions tagged with a company in questions.js are shown on its page automatically.
export const COMPANIES = [
  {
    id: 'google', name: 'Google', sector: 'Technology and AI',
    line: 'The world\'s information layer, rebuilding its products around Gemini.',
    products: ['Search, now with AI-written answers at the top', 'Android, given free to phone makers', 'Google Cloud, the fastest-growing business', 'YouTube, a second huge ad engine', 'Workspace and the Gemini assistant'],
    ai: 'Gemini models for text, images and video; AI answers in Search; agent-style assistants that can research and complete tasks; its own AI chips (TPUs).',
    model: 'Mostly advertising on Search and YouTube, plus Cloud, Play Store commissions, hardware and subscriptions.',
    metrics: ['Search query volume', 'Ad click-through rate and cost per click', 'Daily and monthly active users', 'Cloud revenue retention', 'YouTube watch time, Gemini adoption'],
    competitors: 'Microsoft and OpenAI in AI search; Amazon and Meta in ads; AWS and Azure in cloud; Apple in mobile.',
    know: ['The core tension: AI answers help users but can reduce the ad clicks that fund the company.', 'Part of Alphabet, alongside Waymo and DeepMind.', 'Roadmap focus: product strategy, recent launches, key metrics, culture.'],
  },
  {
    id: 'microsoft', name: 'Microsoft', sector: 'Enterprise software and cloud',
    line: 'The enterprise default, repositioned as an AI company through Copilot.',
    products: ['Azure cloud, the main growth engine', 'Microsoft 365 with Copilot', 'Windows and Surface', 'LinkedIn', 'Xbox and Game Pass'],
    ai: 'Copilot drafts and summarises across Office and code; Copilot agents complete multi-step business workflows with human oversight.',
    model: 'Recurring enterprise revenue: Azure by usage, Microsoft 365 and Copilot per person, Windows licences, LinkedIn and gaming.',
    metrics: ['Azure consumption growth', 'Microsoft 365 seats and Copilot attach rate', 'Net revenue retention', 'Copilot daily usage and task completion'],
    competitors: 'AWS in cloud; Google and Salesforce in productivity; ServiceNow in workflow.',
    know: ['Betting on agentic AI as the next platform shift.', 'The OpenAI partnership is both a strength and a dependency.', 'Roadmap focus: cloud, AI, product portfolio, recent news.'],
  },
  {
    id: 'amazon', name: 'Amazon', sector: 'E-commerce and cloud',
    line: 'Retail, Prime, AWS and devices, run on customer obsession.',
    products: ['Marketplace and retail', 'Prime membership with delivery and Prime Video', 'AWS', 'Alexa and devices', 'Kindle'],
    know: ['Roadmap focus: leadership principles, growth levers, case studies.', 'Past candidates were told to build stories around the leadership principles.', 'Working backwards: write the press release before building.'],
  },
  {
    id: 'adobe', name: 'Adobe', sector: 'Creative software',
    line: 'The professional creative toolkit, betting on Firefly as the safe AI layer.',
    products: ['Creative Cloud: Photoshop, Premiere, Illustrator, Lightroom', 'Document Cloud: Acrobat and e-sign', 'Experience Cloud for marketing teams', 'Firefly generative AI', 'Express, a simple design app'],
    ai: 'Firefly generates images, video and vector art trained on licensed content; assistants in Firefly and Acrobat run multi-step tasks.',
    model: 'Subscriptions across its clouds; growth from new subscribers, higher tiers and paid AI credits.',
    metrics: ['ARR and net new ARR', 'Subscriber growth and churn', 'Firefly usage', 'Revenue per subscriber', 'Free-to-paid conversion on Express'],
    competitors: 'Canva and Figma; Midjourney and OpenAI for images; DocuSign for e-sign.',
    know: ['Open question: does AI grow Adobe\'s market or commoditise content?', 'Famous pivot from boxed software to subscriptions.'],
  },
  {
    id: 'amex', name: 'American Express', sector: 'Payments',
    line: 'A premium card brand that both issues cards and runs its own network.',
    products: ['Consumer cards (Platinum, Gold, Green)', 'Membership Rewards points', 'Business and corporate cards', 'Its own closed-loop network', 'Travel and dining perks'],
    ai: 'Personalised offers, service chat, explaining fraud and credit decisions; preparing for AI agents that pay on a customer\'s behalf.',
    model: 'Merchant fees, annual card fees and lending interest, focused on affluent, low-risk spenders.',
    metrics: ['Card member spend', 'New cards and premium mix', 'Retention and fee revenue', 'Rewards cost vs engagement', 'Credit loss rates'],
    competitors: 'Visa and Mastercard networks; premium issuers.',
    know: ['Closed loop means it sees both shopper and merchant: a real data advantage.', 'Past rounds included a test on logic, SQL/Python and quant.'],
  },
  {
    id: 'booking', name: 'Booking Holdings', sector: 'Online travel',
    line: 'The largest online travel company, building an AI "connected trip".',
    products: ['Booking.com', 'Priceline', 'Agoda', 'Kayak (comparison)', 'OpenTable'],
    ai: 'AI trip planner; moving towards an agent that books flights, stay and car in one conversation.',
    model: 'Commissions on bookings; buying demand efficiently and converting browsers into bookers.',
    metrics: ['Room nights and gross bookings', 'Look-to-book conversion', 'Take rate', 'Marketing return on ad spend', 'Direct app share, repeat bookings'],
    competitors: 'Expedia, Airbnb, Google Travel, Trip.com.',
    know: ['Famously experiment-driven, running huge numbers of A/B tests.', 'Heavy dependence on buying demand from Google.'],
  },
  {
    id: 'ebay', name: 'eBay', sector: 'Marketplace',
    line: 'The original marketplace, refocused on high-value categories with trust and AI listing tools.',
    products: ['Core marketplace (auctions and fixed price)', 'Focus categories: sneakers, luxury, trading cards, auto parts', 'Authenticity guarantee', 'Live shopping and one-photo AI listings', 'Depop'],
    model: 'A take rate on what sells, plus promoted listings and payments.',
    metrics: ['GMV', 'Active buyers and seller retention', 'Take rate', 'Ad revenue', 'Listing creation speed'],
    competitors: 'Amazon, Etsy, resale apps, sneaker marketplaces.',
    know: ['Two-sided: growth means balancing sellers and buyers.', 'Making listing easier with AI directly grows supply.'],
  },
  {
    id: 'sprinklr', name: 'Sprinklr', sector: 'Enterprise SaaS',
    line: 'One AI-native platform for customer experience instead of many point tools.',
    products: ['Social media management', 'AI contact centre', 'Marketing and ads', 'Customer insights', 'Unified platform'],
    model: 'Enterprise subscriptions that grow by adding modules and seats.',
    metrics: ['Net revenue retention', 'Large customers', 'Seat growth', 'AI adoption'],
    competitors: 'Salesforce, Zendesk, social tools.',
    know: ['The pitch is consolidation. Be ready to argue both sides.'],
  },
  {
    id: 'myntra', name: 'Myntra', sector: 'Fashion e-commerce',
    line: 'India\'s leading fashion and lifestyle app, part of the Flipkart group.',
    products: ['Fashion marketplace', 'Discovery and personalisation', 'Beauty', 'Fast fashion delivery', 'Creator-led shopping'],
    ai: 'Styling ideas, conversational discovery, faster catalogue work, a shopping assistant.',
    model: 'Commissions, private-label margins and ads from brands.',
    metrics: ['GMV and orders', 'MAU and conversion', 'Return rate', 'Repeat purchase', 'Ad revenue and private-label mix'],
    competitors: 'Ajio, Nykaa Fashion, Amazon Fashion, Meesho.',
    know: ['Fashion\'s core problem is returns.', 'People browse rather than search in fashion.'],
  },
  {
    id: 'eightfold', name: 'Eightfold.ai', sector: 'HR tech',
    line: 'Matches people to work on skills and potential, not keywords.',
    products: ['Talent acquisition', 'Internal mobility and careers', 'Contract workforce', 'Skills graph platform', 'Build-your-own HR apps'],
    model: 'Enterprise subscriptions across hiring, mobility and planning.',
    metrics: ['Match quality and hire rate', 'Time to fill, cost per hire', 'Internal mobility adoption', 'Net revenue retention', 'Fairness signals'],
    competitors: 'LinkedIn Talent, Workday, SAP SuccessFactors.',
    know: ['AI hiring must balance speed with fairness and explainability.'],
  },
  {
    id: 'jiostar', name: 'JioStar', sector: 'Media',
    line: 'India\'s largest media company, built around JioHotstar and live sports.',
    products: ['JioHotstar streaming', 'Cricket, ICC and Premier League rights', 'TV network', 'Originals and library', 'Ad platform'],
    model: 'Subscriptions plus advertising, with live sports giving pricing power.',
    metrics: ['Paying subscribers and churn', 'Peak concurrent viewers', 'Watch time', 'ARPU', 'Ad fill rate'],
    competitors: 'Netflix, Prime Video, Zee5, SonyLIV, YouTube.',
    know: ['Zero-downtime streaming at cricket scale is the hardest problem.', 'Balancing a free ad tier against premium plans.'],
  },
  {
    id: 'nutanix', name: 'Nutanix', sector: 'Cloud infrastructure',
    line: 'Pools servers, storage and virtualisation into one platform, now for AI on-prem.',
    products: ['Cloud infrastructure', 'Cloud manager', 'Unified storage and databases', 'Kubernetes', 'On-prem AI stack'],
    model: 'Subscription software priced by capacity.',
    metrics: ['ARR', 'Net revenue retention', 'New customers', 'Renewal rate', 'AI workload adoption'],
    competitors: 'VMware (Broadcom), Dell, HPE, public clouds.',
    know: ['Customers leaving VMware after the Broadcom deal is its biggest tailwind.'],
  },
  {
    id: 'acko', name: 'Acko', sector: 'Insurtech',
    line: 'Digital-first insurance with no agents.',
    products: ['Motor insurance', 'Health insurance', 'Embedded cover inside other apps', 'Car buying platform', 'Self-service claims app'],
    model: 'Direct premiums with no agent commissions, plus embedded insurance deals.',
    metrics: ['Gross written premium', 'Claims settlement ratio and time', 'Loss ratio', 'CAC and renewal rate', 'Cross-sell'],
    competitors: 'PolicyBazaar, Digit, traditional insurers.',
    know: ['With no agents, trust is the product: the claims experience does the reassuring.'],
  },
  {
    id: 'pinelabs', name: 'Pine Labs', sector: 'Merchant payments',
    line: 'In-store and online payment infrastructure for merchants.',
    products: ['POS terminals', 'Online payment gateway', 'Gift cards and prepaid', 'EMI and pay later', 'Merchant software'],
    model: 'Fees on payments, device and software subscriptions, BNPL and gift-card revenue.',
    metrics: ['Total payment volume', 'Active merchants and devices', 'Take rate', 'Revenue per merchant'],
    competitors: 'Razorpay, PayU, Paytm, Adyen.',
    know: ['Strong in offline, in-store payments, which is a different game from online-only fintechs.'],
  },
  {
    id: 'ukg', name: 'UKG', sector: 'HR tech',
    line: 'Payroll, HR and workforce management, strongest for hourly and frontline workers.',
    products: ['HR and payroll suite', 'Workforce scheduling', 'SMB all-in-one', 'AI agents for HR tasks', 'AI-assisted payroll'],
    model: 'Subscriptions priced per employee and module.',
    metrics: ['Employees under management', 'Net revenue retention', 'Renewals', 'AI adoption', 'Implementation time'],
    competitors: 'Workday, ADP, SAP SuccessFactors, Dayforce.',
    know: ['Payroll is unforgiving: trust and compliance come first.'],
  },
  {
    id: 'samsung', name: 'Samsung R&D', sector: 'Consumer electronics',
    line: 'Builds the software and AI inside Galaxy devices.',
    products: ['One UI', 'Galaxy AI', 'Camera software', 'Connectivity and multimedia'],
    model: 'An internal R&D centre; money is made on device sales and services.',
    metrics: ['Feature adoption', 'Software stability', 'Galaxy AI usage', 'Language coverage'],
    competitors: 'Apple, Google Pixel, Xiaomi, OnePlus.',
    know: ['Designing for a global product used in many languages.', 'Standing out when Google\'s AI ships on the same phone.'],
  },
  {
    id: 'swiggy', name: 'Swiggy', sector: 'Food and quick commerce',
    line: 'Food delivery plus Instamart quick commerce.',
    know: ['Roadmap focus: business model, unit economics, recent initiatives.'],
  },
  {
    id: 'netflix', name: 'Netflix', sector: 'Streaming',
    line: 'Global subscription streaming.',
    know: ['Roadmap focus: user growth, content strategy, the India opportunity.'],
  },
  {
    id: 'eternal', name: 'Zomato (Eternal)', sector: 'Food and quick commerce',
    line: 'Zomato food delivery and Blinkit quick commerce.',
    know: ['Roadmap focus: food delivery dynamics, profitability, competition.'],
  },
  { id: 'uber', name: 'Uber', sector: 'Mobility', line: 'Ride hailing and delivery.' },
  { id: 'ola', name: 'Ola', sector: 'Mobility and EVs', line: 'Ride hailing and electric scooters.' },
  { id: 'medianet', name: 'Media.net', sector: 'Ad tech', line: 'Contextual advertising technology.' },
  { id: 'salesforce', name: 'Salesforce', sector: 'Enterprise SaaS', line: 'CRM and enterprise cloud software.' },
  { id: 'optum', name: 'Optum', sector: 'Health tech', line: 'Health services and technology arm of UnitedHealth Group.' },
  { id: 'ea', name: 'Electronic Arts', sector: 'Gaming', line: 'Video games publisher. Past rounds went deep on case submissions.' },
]

// Map question company tags to company ids.
export const COMPANY_ALIASES = {
  Google: 'google', Microsoft: 'microsoft', Amazon: 'amazon', Adobe: 'adobe', 'American Express': 'amex',
  'Booking Holdings': 'booking', eBay: 'ebay', Myntra: 'myntra', Samsung: 'samsung', Netflix: 'netflix',
  Eternal: 'eternal', Uber: 'uber', Ola: 'ola', 'Media.net': 'medianet', Salesforce: 'salesforce',
  Optum: 'optum', 'Electronic Arts': 'ea',
}

// Words in a question that link it to a company (case-sensitive).
export const COMPANY_MATCH = {
  google: ['Google', 'YouTube', 'Gmail'], microsoft: ['Microsoft', 'Azure', 'PowerPoint', 'Teams'],
  amazon: ['Amazon', 'Kindle', 'Alexa'], adobe: ['Adobe'], amex: ['Amex', 'American Express'],
  booking: ['Booking.com'], ebay: ['eBay'], myntra: ['Myntra'], samsung: ['Samsung'], swiggy: ['Swiggy'],
  netflix: ['Netflix'], eternal: ['Zomato', 'Blinkit'], uber: ['Uber'], ola: ['Ola'], jiostar: ['Hotstar'],
  ea: ['Clash of Clans'],
}
