// Practice question bank. t = case type, l = difficulty (when known), c = company it was asked at or is about.
const Q = (t, q, l, c) => ({ t, q, l, c })

export const QUESTIONS = [
  // ---------- Product design ----------
  Q('design', 'Design an app to help parents manage their children\'s karate class activities', 'Easy'),
  Q('design', 'Design an app for the cooking needs of people living in urban areas', 'Easy'),
  Q('design', 'Design a product for pet owners', 'Easy'),
  Q('design', 'Design an app to delight visitors of a theme park', 'Easy'),
  Q('design', 'Design an app to increase sports adoption in India', 'Easy'),
  Q('design', 'Design a product to fix long queues at supermarkets', 'Easy', 'DP World'),
  Q('design', 'Design billing software for retail stores and supermarkets', 'Medium'),
  Q('design', 'Design a refrigerator for kids', 'Medium', 'Samsung'),
  Q('design', 'Design an AI product to improve work-life balance and productivity of remote workers', 'Medium', 'Microsoft'),
  Q('design', 'Design a tablet for kids', 'Medium', 'Google'),
  Q('design', 'Design a social media app for elderly people', 'Medium'),
  Q('design', 'Design an ATM for the departure terminal of an airport', 'Medium'),
  Q('design', 'The CEO of a traditional hypermarket asks you to modernise the store. How would you proceed?', 'Medium', 'JPMC'),
  Q('design', 'Design an e-commerce experience for the elderly', 'Medium'),
  Q('design', 'Design a chess app for complete beginners', 'Medium', 'Samsung'),
  Q('design', 'Design the Netflix home page for brand new users', 'Medium', 'Netflix'),
  Q('design', 'Design an airport check-in system', 'Medium'),
  Q('design', 'Create a credit platform for teenagers', 'Hard'),
  Q('design', 'Uber wants to enter pooled student commuting in the US. Design the product', 'Hard', 'Uber'),
  Q('design', 'Design a classroom in the metaverse that brings back human connection', 'Hard', 'Google'),
  Q('design', 'Design a self-driving car for kids in India', 'Hard', 'Google'),
  Q('design', 'Design a car for deaf drivers', 'Hard'),
  Q('design', 'Design a LinkedIn for blue-collar workers in India', 'Hard'),
  Q('design', 'Design a platform to improve patient engagement across the healthcare journey', 'Hard', 'Salesforce'),
  Q('design', 'Design an AI assistant to support doctors in small and medium clinics', 'Hard'),
  Q('design', 'Design a campus recruitment system for a business school', 'Hard'),
  Q('design', 'Design a metrics dashboard for Uber\'s COO', 'Hard', 'Uber'),
  Q('design', 'Design a banking app for rural India to reduce crowding at branches', 'Hard'),
  Q('design', 'Design a marketplace for brands to find and work with content creators', 'Hard'),
  Q('design', 'Unify discovering, planning and attending local events across Google Maps and Google Pay', 'Hard', 'Google'),
  Q('design', 'Design a product that helps organisations hire better', 'Hard'),
  Q('design', 'Design a mobile app for Airbnb\'s office space sharing business'),
  Q('design', 'Design a product to increase voter turnout'),
  Q('design', 'Design a better Disney theme park experience'),
  Q('design', 'Design a startup growth hub for LinkedIn'),
  Q('design', 'Design an Ola-style ride service for school kids'),
  Q('design', 'Design an in-flight entertainment system'),
  Q('design', 'Design a podcast experience inside Spotify'),
  Q('design', 'Design a health and fitness app for smartphone users'),
  Q('design', 'Design an internal knowledge repository for a company'),
  Q('design', 'Design a book recommendation app'),
  Q('design', 'Improve the experience of Samsung Galaxy Buds'),
  Q('design', 'Design an AI copilot for customer support agents'),
  Q('design', 'Design a vendor management tool for a quick commerce company'),
  Q('design', 'Design a bicycle renting app for a college campus'),
  Q('design', 'Design a marketplace for antiques'),
  Q('design', 'Design smart shoes'),
  Q('design', 'Design a news platform'),
  Q('design', 'Design a product for borrowing and lending between people'),
  Q('design', 'Design parking features for Google Maps', undefined, 'Google'),
  Q('design', 'Design a solo travel companion app for Google', undefined, 'Google'),
  Q('design', 'Design a mental wellness tracker for teenagers'),
  Q('design', 'Design a vendor management tool for a B2B company'),
  Q('design', 'Design a product for students to split expenses'),
  Q('design', 'Design a solution for elderly users to manage medicines'),
  Q('design', 'Design a product for travellers with delayed flights'),
  Q('design', 'Design an intelligent table for restaurants'),
  Q('design', 'Design an app for trek enthusiasts'),
  Q('design', 'Design a photo app for blind users'),
  Q('design', 'Design a parenting product'),
  Q('design', 'Design a product for drivers stuck in rush hour'),
  Q('design', 'Design a dating app for students on a business-school campus'),
  Q('design', 'Design YouTube for pets, focusing on viewership and monetisation', undefined, 'Adobe'),
  Q('design', 'It\'s 2010 and only Google Search and Gmail exist. Build the Google productivity suite from scratch', undefined, 'Adobe'),
  Q('design', 'Design a ride-hailing app for underserved users, with a GTM plan and MVP', undefined, 'Microsoft'),
  Q('design', 'Design an app for a mother to teach phonetics to her baby', undefined, 'Cloudnine'),
  Q('design', 'Design an alerting system for a credit provider to catch bad credit, with the user journey', undefined, 'Media.net'),
  Q('design', 'Design a recommendation engine for Swiggy', undefined, 'Media.net'),
  Q('design', 'Solve for rising potholes in a city as a business, with mockups and a data model', undefined, 'Salesforce'),
  Q('design', 'Design a product for astrology', undefined, 'American Express'),
  Q('design', 'Build an application for a college moving its admissions online', undefined, 'Optum'),
  Q('design', 'Design a product for senior citizens'),
  Q('design', 'Help a small pizza shop go digital'),

  // ---------- Product improvement ----------
  Q('improve', 'Improve the product design of Uber', 'Easy', 'Adobe'),
  Q('improve', 'HealthifyMe is seeing low engagement. How would you improve it?', 'Easy'),
  Q('improve', 'How would you improve Spotify? Pick one area to strengthen', 'Easy'),
  Q('improve', 'Improve Google Calendar', 'Easy', 'Google'),
  Q('improve', 'Improve the experience of an OTT platform like Hotstar to build loyalty', 'Easy'),
  Q('improve', 'Improve a ride-hailing app like Ola: more usage and satisfaction', 'Easy', 'Ola'),
  Q('improve', 'Use AI to significantly increase customer engagement on Myntra', 'Medium', 'Myntra'),
  Q('improve', 'Improve the Booking.com app for property owners who list hotels or homestays', 'Medium', 'Booking Holdings'),
  Q('improve', 'Improve a bank\'s mobile app to prevent fraud', 'Medium'),
  Q('improve', 'Create or update an Instagram feature using AI', 'Medium'),
  Q('improve', 'How would you improve Google Maps?', 'Medium', 'Google'),
  Q('improve', 'What is your favourite UPI app and how would you improve it?', 'Medium'),
  Q('improve', 'Users buy books on Kindle and then drop off. Improve Kindle', 'Medium', 'Amazon'),
  Q('improve', 'Improve YouTube on a product metric of your choice', 'Medium', 'Google'),
  Q('improve', 'Improve the MakeMyTrip travel booking app', 'Medium'),
  Q('improve', 'Improve Tinder', 'Medium'),
  Q('improve', 'Improve Swiggy for urban consumers', 'Medium'),
  Q('improve', 'Improve Microsoft PowerPoint', 'Hard', 'Microsoft'),
  Q('improve', 'Design Amazon\'s order notification system as if building it for the first time', 'Hard', 'Amazon'),
  Q('improve', 'Improve browsing and checkout on Myntra for millennials and Gen Z', 'Hard', 'Myntra'),
  Q('improve', 'Suggest AI features to improve a team collaboration platform', 'Hard', 'Microsoft'),
  Q('improve', 'Improve Spotify with an AI-driven remix and DJ experience'),
  Q('improve', 'Make Amazon Prime Video more family-friendly', undefined, 'Amazon'),
  Q('improve', 'Improve MakeMyTrip\'s intercity cab platform in India'),
  Q('improve', 'Improve WhatsApp'),
  Q('improve', 'Improve WhatsApp for older people', undefined, 'Adobe'),
  Q('improve', 'Improve Adobe Scan', undefined, 'Adobe'),
  Q('improve', 'Improve engagement for Headspace'),
  Q('improve', 'Improve Instagram Stories'),
  Q('improve', 'Improve a UPI payments app like PhonePe'),
  Q('improve', 'Improve the Swiggy home screen'),
  Q('improve', 'Improve Swiggy search'),
  Q('improve', 'Improve Spotify discovery'),
  Q('improve', 'Improve LinkedIn networking for MBA students'),
  Q('improve', 'How would you improve Swiggy One?'),
  Q('improve', 'Improve user engagement on BookMyShow'),
  Q('improve', 'Rethink Facebook reactions'),
  Q('improve', 'Improve the American Express mobile app', undefined, 'American Express'),
  Q('improve', 'Many teams want their feature on the Amex app home screen. Decide what shows first', undefined, 'American Express'),
  Q('improve', 'Improve the airport experience', undefined, 'Eternal'),
  Q('improve', 'How would you fix the cart issue on Zepto?', undefined, 'Cloudnine'),
  Q('improve', 'Improve LinkedIn'),
  Q('improve', 'Improve the phone you use every day, then market it using AI', undefined, 'Adobe'),

  // ---------- App analysis ----------
  Q('app', 'Analyse Duolingo'),
  Q('app', 'Analyse Amazon Alexa', undefined, 'Amazon'),
  Q('app', 'Analyse Google Fit', undefined, 'Google'),
  Q('app', 'Analyse Microsoft Teams', undefined, 'Microsoft'),
  Q('app', 'Analyse LinkedIn'),
  Q('app', 'Analyse Zerodha'),
  Q('app', 'Analyse Blinkit'),
  Q('app', 'Analyse Perplexity AI'),
  Q('app', 'Analyse PhonePe'),
  Q('app', 'Critique the Amazon app', undefined, 'Amazon'),
  Q('app', 'Critique Google Maps', undefined, 'Google'),
  Q('app', 'Critique Spotify'),
  Q('app', 'Analyse Myntra and how it can grow revenue', undefined, 'Adobe'),
  Q('app', 'What is your favourite app? What would you improve, and what is its revenue model?', undefined, 'Microsoft'),
  Q('app', 'What is your favourite fintech app and its best feature?', undefined, 'Media.net'),
  Q('app', 'How would you monetise GenAI in your favourite app?', undefined, 'Adobe'),
  Q('app', 'Cricbuzz vs Cricinfo: what sets your favourite apart from its competitor?', undefined, 'Electronic Arts'),

  // ---------- Root cause analysis ----------
  Q('rca', 'Orders on BigBasket\'s quick delivery service have dropped. Find out why', 'Easy'),
  Q('rca', 'Google Maps ETAs have become less accurate. Why?', 'Easy', 'Google'),
  Q('rca', 'Unique daily video uploads on YouTube stopped growing over two weeks. Why?', 'Easy', 'Google'),
  Q('rca', 'Swiggy reports a 10% drop in revenue. How would you tackle it?', 'Medium'),
  Q('rca', 'User-generated content on Flipkart has dropped. Why?', 'Medium'),
  Q('rca', 'Return rate for Amazon products has gone up. What can be done?', 'Medium', 'Amazon'),
  Q('rca', 'The open rate of Flipkart push notifications is down. What would you do?', 'Medium'),
  Q('rca', 'Drivers on Uber have fallen by 2%. What would you do?', 'Medium', 'Uber'),
  Q('rca', 'A quick commerce platform has seen a steady drop in sales for six weeks. Walk me through it', 'Medium'),
  Q('rca', 'Adobe\'s LMS free-trial to paid conversion is 4–5% vs an industry 7–10%. Improve it', 'Medium', 'Adobe'),
  Q('rca', 'Video views on Prime Video have gone down. What should we do?', 'Hard', 'Microsoft'),
  Q('rca', 'Zepto\'s delivery times have gone up. Why?', 'Hard'),
  Q('rca', 'Instagram\'s daily app open rate has dropped. Why?', 'Hard'),
  Q('rca', 'Customer-initiated cancellations on Zomato rose 4–5% in a few weeks. Approach it', 'Hard', 'Eternal'),
  Q('rca', 'Orders on an e-pharmacy app have dropped. Find the cause', 'Hard'),
  Q('rca', 'Bookings on Urban Company have declined'),
  Q('rca', 'Sales of a Samsung phone model have dropped', undefined, 'Samsung'),
  Q('rca', 'Usage of Facebook groups is down 15%'),
  Q('rca', 'Ride cancellations on Ola have increased', undefined, 'Ola'),
  Q('rca', 'Profile views on LinkedIn have dropped'),
  Q('rca', 'Paid subscriptions on Hulu have dropped'),
  Q('rca', 'Ride completion on Ola has dropped', undefined, 'Ola'),
  Q('rca', 'Acceptance of GitHub Copilot suggestions has dropped'),
  Q('rca', 'A B2B SaaS product is seeing rising customer churn'),
  Q('rca', 'Engagement on an app has dropped over the past month'),
  Q('rca', 'A new feature has a low adoption rate'),
  Q('rca', 'Ride cancellations spiked this week'),
  Q('rca', 'Subscriptions to a streaming service are declining'),
  Q('rca', 'Daily active users have dropped'),
  Q('rca', 'Cart additions on an e-commerce app are declining'),
  Q('rca', 'Sales reps are not adopting the new CRM'),
  Q('rca', 'Users are abandoning our AI chatbot'),
  Q('rca', 'A key metric for a streaming service dropped 80%. Find the root cause'),
  Q('rca', 'Daily active users dropped 20% last week. Walk me through your investigation'),
  Q('rca', 'Zomato\'s order conversion rate dropped 15% last Tuesday. What happened?', undefined, 'Eternal'),
  Q('rca', 'Bookings on Uber declined 8–9% over the last few days'),
  Q('rca', 'Order cancellations on Myntra rose 10–12% in five days', undefined, 'Myntra'),
  Q('rca', 'Swiggy\'s order completion rate dropped in one city'),
  Q('rca', 'Spotify activation is down for new users'),
  Q('rca', 'Netflix watch time fell among new users', undefined, 'Netflix'),
  Q('rca', 'A fintech app is seeing rising churn'),
  Q('rca', 'Bookings dropped on the Paytm app', undefined, 'Electronic Arts'),
  Q('rca', 'Blinkit revenue fell 20% in a tier-2 city', undefined, 'Electronic Arts'),
  Q('rca', 'Sales of Clash of Clans have gone down. Use funnel analysis', undefined, 'Electronic Arts'),
  Q('rca', 'In-app purchases in a game have gone down. Find the causes', undefined, 'Electronic Arts'),
  Q('rca', 'Amazon orders per day are declining. How would you approach it?', undefined, 'Adobe'),
  Q('rca', 'BookMyShow revenue has dropped', undefined, 'Media.net'),
  Q('rca', 'A data movement product on Azure is not meeting its objectives', undefined, 'Microsoft'),
  Q('rca', 'Why do you think Netflix\'s growth in India has slowed?', undefined, 'Netflix'),

  // ---------- Metrics ----------
  Q('metrics', 'What metrics should Swiggy track end to end?'),
  Q('metrics', 'How would you measure Spotify\'s free-to-premium conversion?'),
  Q('metrics', 'What are the key metrics for Uber?', undefined, 'Uber'),
  Q('metrics', 'How would you measure the health of a B2B SaaS product?'),
  Q('metrics', 'As Swiggy\'s CPO, which product metrics would you monitor ahead of an IPO?'),
  Q('metrics', 'What are the success metrics for Gmail?', undefined, 'Google'),
  Q('metrics', 'How would you measure success of WhatsApp\'s in-app video playing feature?'),
  Q('metrics', 'As a PM at a leading e-commerce company, which metrics would you watch?'),
  Q('metrics', 'Define metrics for an Instagram creator marketplace'),
  Q('metrics', 'Define metrics for Facebook Marketplace'),
  Q('metrics', 'Define metrics for the BigBasket app'),
  Q('metrics', 'How would you measure an AI feature?'),
  Q('metrics', 'Measure the success of promotions in Google Pay', undefined, 'Google'),
  Q('metrics', 'Design a dashboard to track the health of the business'),
  Q('metrics', 'You own a feature. What dashboard would you build to track its effectiveness?'),
  Q('metrics', 'As Uber\'s PM, what dashboard would track the health of the app?', undefined, 'Uber'),
  Q('metrics', 'You own Flipkart\'s cart page. How would you build a dashboard to measure success?'),
  Q('metrics', 'A debit card for drivers just launched. Build its first dashboard'),
  Q('metrics', 'How would you measure whether an AI feature is actually working?'),
  Q('metrics', 'Build a scalable way to get KPIs of 100+ products daily, weekly and monthly', undefined, 'Microsoft'),
  Q('metrics', 'How do you define success of a feature your team launched?', undefined, 'Optum'),

  // ---------- GTM ----------
  Q('gtm', 'Plan the GTM for a home-cooked meal delivery app launched by Myntra', undefined, 'Myntra'),
  Q('gtm', 'How would you launch a product recommendation carousel on Amazon?', undefined, 'Amazon'),
  Q('gtm', 'How would you launch a standalone Amazon restaurant food delivery app?', undefined, 'Amazon'),
  Q('gtm', 'Come up with a launch strategy for a Google laptop', undefined, 'Google'),
  Q('gtm', 'GTM for a social fitness product'),
  Q('gtm', 'GTM for a table reservation product'),
  Q('gtm', 'Launch an AI sales assistant'),
  Q('gtm', 'Design a loyalty program for the Tata Group'),
  Q('gtm', 'GTM for a fitness app'),
  Q('gtm', 'GTM for a physical device'),
  Q('gtm', 'GTM for a technical B2B product'),
  Q('gtm', 'GTM for a social media app'),
  Q('gtm', 'MakeMyTrip wants to enter Dubai. What should the market entry strategy be?'),
  Q('gtm', 'Launch a new product in a new market'),
  Q('gtm', 'Grow an existing product in a target segment'),
  Q('gtm', 'Design a partnership or channel strategy for a product'),
  Q('gtm', 'Design the GTM for eBay exports', undefined, 'eBay'),
  Q('gtm', 'GTM for Amazon in lending', undefined, 'Media.net'),
  Q('gtm', 'GTM for a new product that already has strong competitors', undefined, 'Microsoft'),
  Q('gtm', 'Should Cricbuzz launch a separate football app? Size the market too', undefined, 'Electronic Arts'),
  Q('gtm', 'Ola launched a new electric bike. How would you grow its sales and measure success?', undefined, 'Ola'),
  Q('gtm', 'Launch a new food delivery product that could take on Swiggy and Zomato'),

  // ---------- Prioritisation ----------
  Q('prioritisation', 'Prioritise features for the next quarter'),
  Q('prioritisation', 'Allocate resources across multiple opportunities'),
  Q('prioritisation', 'Decide what to build, defer or drop from a long backlog'),
  Q('prioritisation', 'Your engineering manager wants a new feature and you have no bandwidth. What do you do?'),
  Q('prioritisation', 'A customer wants a feature and engineering says it can\'t be built. How do you proceed?', undefined, 'Microsoft'),
  Q('prioritisation', 'Your only developer is on sick leave on release day. What do you do?', undefined, 'Marico'),
  Q('prioritisation', 'Delivering faster vs delivering a better product: which do you choose?'),
  Q('prioritisation', 'Azure is retiring a service your product depends on. How do you handle it?', undefined, 'Microsoft'),

  // ---------- Pricing ----------
  Q('pricing', 'How would you price a family plan for JioSaavn?', 'Easy'),
  Q('pricing', 'How would you price Apple\'s smart speaker?', 'Easy'),
  Q('pricing', 'How would you price Amazon Prime?', 'Medium', 'Amazon'),
  Q('pricing', 'Project the right price for Amazon Prime in India', undefined, 'Amazon'),
  Q('pricing', 'Set Netflix\'s pricing strategy for India', undefined, 'Netflix'),
  Q('pricing', 'Negotiate prices with a vendor'),
  Q('pricing', 'Price a subscription-based product'),
  Q('pricing', 'Price Spotify Premium'),
  Q('pricing', 'How do you price a new product? Walk through the strategies', undefined, 'Optum'),
  Q('pricing', 'eBay offers suppliers 10% off commission for upfront payment. Is it feasible?', undefined, 'eBay'),
  Q('pricing', 'If one AI product and one non-AI product launch, how does your pricing differ?'),

  // ---------- Strategy ----------
  Q('strategy', 'Should PhonePe expand into lending?'),
  Q('strategy', 'Should Google enter the OTT market?', undefined, 'Google'),
  Q('strategy', 'Should Facebook consolidate all its messaging apps?'),
  Q('strategy', 'How would you increase Airbnb bookings?'),
  Q('strategy', 'How do you stop people moving from WhatsApp to Telegram?'),
  Q('strategy', 'How would you stop fake products being sold on Instagram?'),
  Q('strategy', 'Should quick commerce platforms expand into financial services?'),
  Q('strategy', 'How can agentic AI be used in fintech?'),
  Q('strategy', 'Do credit cards face competition from BNPL?', undefined, 'American Express'),
  Q('strategy', 'How would you choose a location for a dark store?', undefined, 'Eternal'),
  Q('strategy', 'Convince a young man new to the city to join Zomato or Blinkit as a delivery partner', undefined, 'Eternal'),
  Q('strategy', 'Treat Microsoft as a country defending its territory. How would you protect market share?', undefined, 'Microsoft'),
  Q('strategy', 'Europe and India have different data privacy rules. Find a solution that satisfies both', undefined, 'Microsoft'),
  Q('strategy', 'Ola needs to cut scooter delivery lead time. Present a plan to the CEO', undefined, 'Ola'),

  // ---------- Moonshot ----------
  Q('moonshot', 'Design the next smartphone after touchscreens'),
  Q('moonshot', 'End food wastage in India'),
  Q('moonshot', 'Eliminate road accidents in the world'),
  Q('moonshot', 'Reinvent education for rural India'),
  Q('moonshot', 'With unlimited resources, help every genuinely funny person make money from their humour'),

  // ---------- Guesstimates ----------
  Q('guesstimate', 'Estimate the number of WhatsApp chats', 'Easy'),
  Q('guesstimate', 'How much storage does Google Photos need?', 'Easy', 'Google'),
  Q('guesstimate', 'How many Uber drivers are there in Bangalore?', 'Easy', 'Samsung'),
  Q('guesstimate', 'Total storage needed to give 200 GB free Google Drive to people in Singapore', 'Easy', 'Google'),
  Q('guesstimate', 'You\'re starting a bike taxi company. How many bikes do you need?', 'Medium', 'Google'),
  Q('guesstimate', 'How many queries does Google answer per second?', 'Medium', 'Google'),
  Q('guesstimate', 'How many orders does Swiggy deliver per hour in India?', 'Medium'),
  Q('guesstimate', 'Estimate the number of Google Meet calls', 'Medium', 'Google'),
  Q('guesstimate', 'Estimate potential users of a Bhojpuri short-movie app', 'Hard'),
  Q('guesstimate', 'Estimate Instagram posts uploaded in India per day'),
  Q('guesstimate', 'Estimate YouTube\'s daily revenue', undefined, 'Google'),
  Q('guesstimate', 'Estimate Zoom\'s daily server usage'),
  Q('guesstimate', 'Estimate users of a food delivery app in a South American country'),
  Q('guesstimate', 'How many dark stores give 10-minute coverage of a city like Ahmedabad?'),
  Q('guesstimate', 'How many restaurants are listed on Zomato?'),
  Q('guesstimate', 'Estimate video consultations on Practo'),
  Q('guesstimate', 'Estimate ChatGPT queries in India'),
  Q('guesstimate', 'Estimate Zepto\'s annual gross order value'),
  Q('guesstimate', 'Estimate total daily orders on Zomato and Swiggy'),
  Q('guesstimate', 'Estimate the number of flights taking off from Bengaluru airport in a day'),
  Q('guesstimate', 'How much money is spent on gas in the US every year?'),
  Q('guesstimate', 'Estimate the market size of quick commerce in India'),
  Q('guesstimate', 'Number of Uber rides in a day in Bengaluru'),
  Q('guesstimate', 'Estimate the revenue of a D2C brand'),
  Q('guesstimate', 'Number of laptops sold in India annually'),
  Q('guesstimate', 'Estimate the number of online grocery orders in India'),
  Q('guesstimate', 'Estimate WhatsApp messages sent globally', undefined, 'Media.net'),
  Q('guesstimate', 'Number of credit card transactions in India in a month', undefined, 'American Express'),
  Q('guesstimate', 'Users who benefit if a wallet limit rises from 5k to 10k', undefined, 'American Express'),
  Q('guesstimate', 'Estimate food trucks in a city like Bangalore', undefined, 'Eternal'),
  Q('guesstimate', 'Estimate the market size of online food delivery in India'),
  Q('guesstimate', 'Number of coffee cups sold in a day in a city', undefined, 'eBay'),
  Q('guesstimate', 'Number of toothbrushes used in India', undefined, 'Electronic Arts'),
  Q('guesstimate', 'How many e-rickshaws does a city need?', undefined, 'Electronic Arts'),
  Q('guesstimate', 'Estimate pizzas sold in India', undefined, 'American Express'),

  // ---------- Behavioural ----------
  Q('behavioural', 'Why PM? Why now, given your background?'),
  Q('behavioural', 'Describe a time you had to influence a decision without formal authority'),
  Q('behavioural', 'Tell me about a project where things did not go as planned'),
  Q('behavioural', 'Describe a time you had to prioritise between competing demands'),
  Q('behavioural', 'Tell me about a time you used data to drive a decision'),
  Q('behavioural', 'Describe a time you received critical feedback. How did you respond?'),
  Q('behavioural', 'Tell me about a time you worked with teams that had different priorities'),
  Q('behavioural', 'Where do you see yourself in 5 years, and how does this role fit?'),
  Q('behavioural', 'Tell me about a time you made a decision with incomplete information'),
  Q('behavioural', 'Tell me about a time you led a project'),
  Q('behavioural', 'Describe a conflict and how you handled it'),
  Q('behavioural', 'What was your biggest failure?'),
  Q('behavioural', 'Tell me about a time you made a short-term sacrifice for long-term gain'),
  Q('behavioural', 'What is the toughest problem you solved in your last role?'),
  Q('behavioural', 'What excites you about product management?'),
  Q('behavioural', 'What if you don\'t get into product management?'),
  Q('behavioural', 'You don\'t have tech work experience. Why are you a fit?'),
  Q('behavioural', 'Why do you want to work at our company?'),
  Q('behavioural', 'Tell me about a time you used data to influence an important stakeholder'),
  Q('behavioural', 'Have you used AI in your work or studies? What was the outcome?'),
  Q('behavioural', 'An AI feature you shipped is wrong 20% of the time. What do you do?'),
  Q('behavioural', 'Tell me about a time you said no to an AI feature request'),
  Q('behavioural', 'Tell me about a time you took ownership beyond your role', undefined, 'Amazon'),
  Q('behavioural', 'Tell me about a time you convinced a peer', undefined, 'Amazon'),
  Q('behavioural', 'Tell me about a time you managed ego clashes in your team', undefined, 'Microsoft'),
  Q('behavioural', 'What do you do when peers or managers contradict you?', undefined, 'Google'),
  Q('behavioural', 'Tell me about an ethical value you stood up for', undefined, 'Google'),
  Q('behavioural', 'Tell me about a goal you set and failed to achieve', undefined, 'Google'),
  Q('behavioural', 'Tell me about a time you failed to keep stakeholders updated', undefined, 'Google'),
  Q('behavioural', 'Tell me about a time you managed someone more senior than you', undefined, 'Marico'),
  Q('behavioural', 'Tell me about your previous company\'s product and what you\'d change'),
]
