// Sector primers: who plays, how money is made, what PMs measure, common pitfalls and interview angles.
export const SECTORS = [
  {
    id: 'qcom', name: 'Quick commerce',
    players: 'India: Blinkit, Swiggy Instamart, Zepto, BBNow. Global: Gopuff, Getir, Flink.',
    model: 'Dark stores within 1–3 km of dense demand, a few thousand SKUs, 10–20 minute delivery. Earns from delivery and platform fees, subscriptions, on-app ads for brands and product margins.',
    metrics: ['Orders, AOV, monthly active users', 'On-time %, ETA accuracy, fill rate (no stock-outs)', 'Contribution margin per order, CAC, payback', 'Complaints, cold-chain breaches, promo abuse'],
    pitfalls: ['Deep discounts that burn cash', 'Expanding into low-density areas too fast', 'Promising ETAs you can\'t keep', 'Ads that clutter the app and hurt purchase intent'],
    angles: ['Work out contribution margin per order live from AOV, delivery, packing, discount and ad revenue', 'Where to open the next five dark stores: coverage vs cannibalisation', 'Raise order value without slowing delivery: bundles, free-delivery thresholds', 'Reliability over raw speed: proactive delay messages'],
  },
  {
    id: 'fintech', name: 'Fintech',
    players: 'Payments: PhonePe, Google Pay, Paytm, CRED. Wealth: Zerodha, Groww. Lending and BNPL: Simpl, LazyPay. Insurance: PolicyBazaar, Acko, Digit. B2B: Razorpay, PayU, Pine Labs.',
    model: 'Payments earn merchant fees; lending earns interest margin and processing fees; wealth earns brokerage or subscriptions; infrastructure earns API and SaaS fees.',
    metrics: ['MAU, transaction volume', 'LTV to CAC above 3, contribution margin', 'Authorisation rate above 95%, chargebacks, uptime', 'KYC drop-off, NPS'],
    pitfalls: ['Long or confusing KYC', 'Not understanding the full money flow', 'Compliance as an afterthought', 'Weak fraud defences', 'Cluttering a simple payments app with extras'],
    angles: ['Start design answers from regulatory guardrails', 'Anchor on trust, not just growth', 'Whiteboard a transaction from tap to settlement', 'Plan for failure: what happens when a UPI payment fails?'],
  },
  {
    id: 'travel', name: 'Travel tech',
    players: 'India: MakeMyTrip, Yatra, Cleartrip, EaseMyTrip. Global: Booking Holdings, Expedia, Trip.com. Others: Airbnb, Skyscanner, Google Flights.',
    model: 'Low-margin, high-volume marketplaces aggregating fragmented supply. Earn commissions, fees, ads and add-ons like insurance and cancellation cover.',
    metrics: ['Search-to-book conversion, bookings per user, repeat rate', 'Cancellations, refund turnaround, ratings', 'Commission retained, CAC, contribution margin', 'Fraud, fake reviews'],
    pitfalls: ['Commoditisation and discount wars', 'Refund and support nightmares', 'Hotels and airlines pushing direct booking', 'Too many verticals, diluted experience'],
    angles: ['Redesign booking to cut drop-offs', 'Keep a hotel chain that wants to pay less commission', 'Speed of expansion vs depth of local supply'],
  },
  {
    id: 'food', name: 'Food tech',
    players: 'Swiggy, Zomato, cloud kitchens like Rebel Foods, restaurant software like PetPooja.',
    model: 'Two or three-sided marketplace (diners, restaurants, couriers) with thin margins and high frequency. Earns commissions, delivery fees, subscriptions, ads and B2B supply.',
    metrics: ['Active users, orders, AOV, membership uptake', 'On-time delivery, ETA accuracy, prep time, cancellations', 'Take rate, delivery cost per order, contribution margin', 'Complaints, food safety, promo abuse'],
    pitfalls: ['Discount addiction', 'Fast dispatch but slow kitchens', 'Poor menus and images', 'Slow refunds', 'Ad overload'],
    angles: ['Unit economics from AOV, commission, delivery, discounts', 'Speed vs reliability: prep-time SLAs, delay credits', 'Reduce cancellations: live inventory sync, rerouting'],
  },
  {
    id: 'ecom', name: 'E-commerce',
    players: 'India: Flipkart and Myntra, Amazon, Meesho, JioMart and Ajio. Global: Alibaba, Amazon, Pinduoduo.',
    model: 'Inventory-led or marketplace. Earns commissions, ads, subscriptions, fulfilment fees and private-label margins.',
    metrics: ['GMV, AOV, cart abandonment, category mix', 'On-time delivery, return and cancellation rates', 'Contribution margin, take rate, lifetime value', 'Ad CTR and return on ad spend', 'Counterfeit complaints'],
    pitfalls: ['Poor listings and misclassified products', 'Uncompetitive pricing', 'Fake products and reviews', 'Wasted ad slots', 'Forecasting errors'],
    angles: ['Diagnose high cart abandonment in one category', 'Redesign apparel returns at a 40% return rate', 'Catch counterfeits before they ship', 'Allocate limited ad slots during big sale days'],
  },
  {
    id: 'ott', name: 'OTT and streaming',
    players: 'Netflix, Prime Video, JioHotstar, Zee5, SonyLIV, regional apps like aha and Hoichoi.',
    model: 'Subscription (SVOD), ad-supported (AVOD), pay-per-view (TVOD) or freemium. Live sports drive growth.',
    metrics: ['Subscriber growth and churn', 'Watch time, completion rate, binge rate', 'Buffering rate, video start time', 'ARPU, content cost per hour'],
    pitfalls: ['Weak discovery and repetitive recommendations', 'Buffering during traffic spikes', 'Piracy', 'Irritating ads', 'No sync across devices'],
    angles: ['New users watching under an hour in week one: diagnose churn risk', 'Endless scrolling without watching: fix recommendations', 'Place limited ad slots during big events'],
  },
  {
    id: 'mobility', name: 'Ride hailing',
    players: 'Uber, Ola, Rapido, Namma Yatri. Corporate: Uber for Business, Ola Corporate.',
    model: 'Commission per trip, subscriptions, corporate contracts, in-app ads.',
    metrics: ['Rides, gross booking value, active users', 'Completion and cancellation rates, match time, ETA accuracy', 'Driver utilisation and earnings per hour', 'Safety incidents per million rides'],
    pitfalls: ['Slow matching', 'Drivers in the wrong places', 'Opaque surge pricing', 'Unrestricted driver cancellations', 'Weak safety features'],
    angles: ['Drivers avoid a busy airport zone: fix supply', 'Drivers switch to rival apps in surge zones', 'Low SOS adoption: redesign safety'],
  },
  {
    id: 'saas', name: 'B2B SaaS',
    players: 'Freshworks, Zoho, Darwinbox, Chargebee; vertical SaaS like Zenoti and Innovaccer.',
    model: 'Recurring subscriptions tiered by features, users or usage. Grows through product-led self-serve or sales-led enterprise deals.',
    metrics: ['ARR and MRR', 'LTV to CAC above 3, payback under 12–18 months', 'Net revenue retention above 120% for the best', 'Activation rate, NPS'],
    pitfalls: ['A nice-to-have, not a painkiller', 'Wrong go-to-market for the product', 'Missing enterprise basics like SSO and audit logs', 'Poor onboarding'],
    angles: ['Ask: product-led or sales-led?', 'Separate the buyer (ROI) from the end user (workflow)', 'Grow through expansion revenue'],
  },
  {
    id: 'devtools', name: 'Developer tools',
    players: 'GitHub, GitLab, JetBrains, BrowserStack, Postman, Datadog.',
    model: 'Generous free tiers, then usage-based or per-seat pricing. Communities and documentation are part of the product.',
    metrics: ['Weekly active users or teams', 'Activation (first successful build), time to value', 'Net revenue retention', 'LTV to CAC'],
    pitfalls: ['Poor developer experience', 'Ignoring the community', 'Can\'t cross from self-serve to enterprise', 'Solving a niche problem'],
    angles: ['Think in ecosystems: IDE, repos, chat', 'Community-first go-to-market', 'Explain the product-led flywheel'],
  },
  {
    id: 'health', name: 'Health tech',
    players: 'Practo, Tata 1mg, HealthifyMe, Cult.fit; global Teladoc, Epic.',
    model: 'Consultation commissions, diagnostics, subscriptions, software for hospitals, corporate packages.',
    metrics: ['Free-to-paid conversion, churn, ARPU', 'Wait time, no-show rate, report turnaround', 'Care plan adherence, consultation completion'],
    pitfalls: ['Video drops and device pairing issues', 'Complex UI for older users', 'Weak privacy and consent', 'Steep drop-off after the first month'],
    angles: ['Wellness app usage falls after month one', 'Consults don\'t convert to medicine orders', 'Seniors need help but can\'t use the app'],
  },
  {
    id: 'edtech', name: 'Edtech',
    players: 'PhysicsWallah, upGrad, Unacademy, Coursera, Duolingo.',
    model: 'Freemium, subscriptions or cohort pricing; hybrid live, recorded and offline learning.',
    metrics: ['CAC and conversion', 'Course completion, session time', 'Day-7 and day-30 retention', 'LTV to CAC, NPS'],
    pitfalls: ['High CAC with weak retention', 'Low completion', 'Poor onboarding', 'Weak trust and unclear outcomes'],
    angles: ['Improve retention on a language app', 'Design an AI tutor', 'Increase course completion', 'Learning for tier-2 India'],
  },
  {
    id: 'ai', name: 'AI products',
    players: 'Infrastructure (chips, cloud), foundation models, platforms (RAG, vector databases), applications (assistants, copilots), services and consultancies.',
    model: 'Usage-based pricing per call or token, plus subscriptions for enterprise products.',
    metrics: ['Hallucination rate, p95 latency, accuracy, eval coverage', 'Task success, feature adoption', 'Cost per resolved task, uptime, customer ROI'],
    pitfalls: ['AI without a user problem', 'No safeguards against hallucination', 'Weak evaluation', 'High inference cost', 'Ignoring existing human workflows'],
    angles: ['Start with the user problem', 'Explain why AI is needed', 'Define evals and guardrails', 'Name trade-offs: accuracy vs latency, cost vs quality, personalisation vs privacy'],
  },
]
