// The six-week roadmap. Edit this file to change weeks, targets or questions.

export const FIELD_SETS = {
  product: [
    { name: 'title', label: 'Product', required: true, placeholder: 'e.g. Swiggy' },
    { name: 'industry', label: 'Industry', placeholder: 'e.g. Food delivery' },
    { name: 'flow', label: 'Flow you explored', placeholder: 'e.g. Search to checkout' },
    { name: 'minutes', label: 'Minutes spent', type: 'number' },
    { name: 'notes', label: 'Teardown notes', type: 'textarea', placeholder: 'User problem, key features, business goal, metrics it moves' },
  ],
  feature: [
    { name: 'title', label: 'Feature', required: true, placeholder: 'e.g. Reorder from past orders' },
    { name: 'product', label: 'Product', placeholder: 'e.g. Zomato' },
    { name: 'problem', label: 'User problem it solves', type: 'textarea' },
    { name: 'goal', label: 'Business goal it serves', placeholder: 'e.g. Repeat orders, retention' },
    { name: 'metric', label: 'Metric it could move', placeholder: 'e.g. Orders per user per month' },
  ],
  journey: [
    { name: 'title', label: 'Journey', required: true, placeholder: 'e.g. First order on Blinkit' },
    { name: 'product', label: 'Product' },
    { name: 'steps', label: 'Steps and touchpoints', type: 'textarea', placeholder: 'One step per line' },
    { name: 'friction', label: 'Friction you noticed', type: 'textarea' },
  ],
  metric: [
    { name: 'title', label: 'Metric', required: true, placeholder: 'e.g. Order completion rate' },
    { name: 'product', label: 'Product' },
    { name: 'definition', label: 'How it is calculated', type: 'textarea' },
    { name: 'why', label: 'Why it matters', type: 'textarea' },
  ],
  case: [
    { name: 'title', label: 'Question', required: true, placeholder: 'Paste or write the case prompt' },
    { name: 'minutes', label: 'Minutes spent', type: 'number' },
    { name: 'rating', label: 'How did it go?', type: 'rating' },
    { name: 'notes', label: 'What to do better next time', type: 'textarea' },
  ],
  story: [
    { name: 'title', label: 'Story name', required: true, placeholder: 'e.g. Relaunching the vendor portal' },
    { name: 'themes', label: 'Themes it covers', type: 'tags', options: ['Why PM', 'Influence without authority', 'Things went wrong', 'Competing priorities', 'Data-driven decision', 'Critical feedback', 'Cross-functional work', 'Incomplete information', 'Conflict', 'Leadership', 'Failure', 'Ownership'] },
    { name: 'situation', label: 'Situation', type: 'textarea' },
    { name: 'task', label: 'Task', type: 'textarea' },
    { name: 'action', label: 'Action', type: 'textarea' },
    { name: 'result', label: 'Result', type: 'textarea', placeholder: 'Include a number if you can' },
  ],
  deepdive: [
    { name: 'title', label: 'Product', required: true, placeholder: 'e.g. Spotify' },
    { name: 'why', label: 'Why you love it', type: 'textarea' },
    { name: 'features', label: 'Key features and decisions', type: 'textarea' },
    { name: 'metrics', label: 'Metrics that matter', type: 'textarea' },
    { name: 'strategy', label: 'Strategy and business model', type: 'textarea' },
    { name: 'future', label: 'What you would build next', type: 'textarea' },
    { name: 'minutes', label: 'Minutes spent', type: 'number' },
  ],
  mock: [
    { name: 'title', label: 'Question asked', required: true },
    { name: 'format', label: 'Format', type: 'select', options: ['Product sense', 'Product design', 'RCA', 'Metrics', 'GTM', 'Prioritisation', 'Guesstimate', 'Strategy', 'Behavioural', 'Mixed'] },
    { name: 'with', label: 'Mock partner', placeholder: 'Peer, alum or mentor' },
    { name: 'minutes', label: 'Minutes', type: 'number' },
    { name: 'rating', label: 'Score', type: 'rating' },
    { name: 'feedback', label: 'Feedback received', type: 'textarea' },
  ],
  company: [
    { name: 'title', label: 'Company', required: true, placeholder: 'e.g. Swiggy' },
    { name: 'strategy', label: 'Product strategy', type: 'textarea' },
    { name: 'launches', label: 'Recent launches and news', type: 'textarea' },
    { name: 'metrics', label: 'Key metrics', type: 'textarea' },
    { name: 'why', label: 'Why this company', type: 'textarea' },
    { name: 'minutes', label: 'Minutes spent', type: 'number' },
  ],
  hours: [
    { name: 'title', label: 'What you worked on', required: true, placeholder: 'e.g. Reading on marketplace metrics' },
    { name: 'minutes', label: 'Minutes', type: 'number', required: true },
  ],
}

// A tracker is a counted log. kind decides which fields the form shows.
export const WEEKS = [
  {
    n: 1,
    practice: ['app'],
    slug: 'product-sense',
    title: 'Build product sense',
    short: 'Product sense',
    hours: 20,
    color: 'var(--w1)',
    summary: 'Start seeing products like a PM by analysing how real products solve user problems.',
    means: [
      'Understand the user journey end to end',
      'Spot key features and decision points',
      'Notice metrics, trade-offs and business goals',
      'Compare how similar products solve the same problem',
    ],
    todo: [
      'Analyse 8–10 products across industries',
      'Spend time exploring one key flow in each product',
      'Compare at least 2 competing products',
      'Capture learnings in a simple product teardown note',
    ],
    trackers: [
      { id: 'products', label: 'Products analysed', kind: 'product', min: 8, max: 10 },
      { id: 'features', label: 'Feature bank', kind: 'feature', min: 0, bank: true },
      { id: 'journeys', label: 'Journey bank', kind: 'journey', min: 0, bank: true },
      { id: 'metrics', label: 'Metric bank', kind: 'metric', min: 0, bank: true },
    ],
    suggested: [
      ['Food delivery', 'Swiggy, Zomato'],
      ['Quick commerce', 'Zepto, Blinkit'],
      ['E-commerce', 'Amazon, Flipkart'],
      ['Travel', 'MakeMyTrip, Goibibo'],
      ['Mobility', 'Uber, Rapido'],
      ['Payments', 'PhonePe, Google Pay'],
      ['AI products', 'Claude, ChatGPT, Gemini'],
      ['Music streaming', 'Spotify, Apple Music'],
    ],
    lens: ['What user problem is being solved?', 'What feature enables it?', 'What business goal does it serve?', 'What metric could it impact?'],
    example: {
      title: 'Worked example: a food delivery order',
      steps: [
        ['Discovery', 'Home screen, categories, banners', 'How do users discover restaurants? What drives clicks?'],
        ['Search and listing', 'Search results, restaurant cards', 'How are results ranked? What information helps users choose?'],
        ['Menu', 'Dish list, images, ratings, reviews', 'How is the menu structured? What drives dish selection?'],
        ['Cart', 'Items, quantities, add-ons', 'What friction exists before checkout? How does cart design affect conversion?'],
        ['Upsell and discounts', 'Cross-sell, combos, threshold offers', 'How do these raise order value and conversion?'],
        ['Payment', 'UPI, cards, wallet, pay later', 'Why offer many options? How do they reduce drop-offs?'],
        ['Post-order', 'Tracking, cancellation, refunds, support', 'How is trust built after payment? What happens if something goes wrong?'],
      ],
    },
    outputs: ['Feature bank: features you observed', 'Journey bank: user flows and touchpoints', 'Metric bank: important metrics to track'],
    outcome: 'By the end of the week you can break down any product with structure and confidence.',
  },
  {
    n: 2,
    practice: ['design', 'improve', 'moonshot'],
    slug: 'product-design',
    title: 'Product design',
    short: 'Product design',
    hours: 10,
    color: 'var(--w2)',
    summary: 'Solve product design questions with structured thinking, clear user focus and practical trade-offs.',
    means: [
      'Understand the user before jumping to solutions',
      'Define the problem clearly and prioritise one need',
      'Generate thoughtful solutions, not random features',
      'Explain trade-offs and success metrics',
    ],
    todo: [
      'Practise 10–15 product design cases',
      'Use a simple structure in every answer',
      'Work on both new and existing products',
      'Review your answers and refine your thinking',
    ],
    trackers: [{ id: 'design', label: 'Design cases', kind: 'case', min: 10, max: 15 }],
    approach: [
      ['Clarify', 'Who is the user? What problem are we solving?'],
      ['Target user', 'Choose a segment and understand their needs'],
      ['Prioritise', 'Pick the most important pain point'],
      ['Solution', 'Propose features and explain why'],
      ['Success metrics', 'Define how you would measure impact'],
    ],
    outputs: ['Structured answers, not scattered ideas', 'More comfort with ambiguity', 'A repeatable framework for interviews'],
  },
  {
    n: 3,
    practice: ['rca', 'metrics'],
    slug: 'rca-metrics',
    title: 'Root cause analysis and metrics',
    short: 'RCA and metrics',
    hours: 15,
    color: 'var(--w3)',
    summary: 'Break problems down systematically, find root causes and get comfortable with key product metrics.',
    means: [
      'Break a problem down before jumping to solutions',
      'Separate symptoms from root causes',
      'Use data, funnels and segmentation to form hypotheses',
      'Understand which product metrics matter and why',
    ],
    todo: [
      'Practise 8–10 RCA cases',
      'Learn metrics for about 10 popular products',
      'Use a simple structure in every answer',
      'Review your logic and refine your thinking',
    ],
    trackers: [
      { id: 'rca', label: 'RCA cases', kind: 'case', min: 8, max: 10 },
      { id: 'metricsets', label: 'Metrics mapped (about 10 products)', kind: 'metric', min: 10, bank: true },
      { id: 'metricq', label: 'Metrics questions', kind: 'case', min: 0 },
    ],
    approach: [
      ['Clarify', 'What exactly is the problem?'],
      ['Segment', 'Which user, city, platform or funnel stage?'],
      ['Diagnose', 'Break down metrics and find likely drivers'],
      ['Hypothesise', 'List possible causes and test them'],
      ['Recommend', 'Suggest next steps and what to track'],
    ],
    outputs: ['Structured answers, not scattered ideas', 'More comfort with data and metrics', 'A repeatable framework for interviews'],
  },
  {
    n: 4,
    practice: ['gtm', 'prioritisation', 'pricing', 'strategy'],
    slug: 'gtm-prioritisation',
    title: 'GTM and prioritisation',
    short: 'GTM and prioritisation',
    hours: 18,
    color: 'var(--w4)',
    summary: 'Figure out how to take products to market and make smart trade-offs when resources are limited.',
    means: [
      'Understand how products reach and grow with users',
      'Learn key GTM levers and frameworks',
      'Prioritise features or bets with structured thinking',
      'Make trade-offs across user, business and technical constraints',
    ],
    todo: [
      'Practise 10–15 GTM cases across industries',
      'Solve 5–10 prioritisation cases (feature, product or investment)',
      'Use frameworks like RICE, ICE and MoSCoW',
      'Consider execution, risks and constraints',
      'Review answers and get feedback',
    ],
    trackers: [
      { id: 'gtm', label: 'GTM cases', kind: 'case', min: 10, max: 15 },
      { id: 'prio', label: 'Prioritisation cases', kind: 'case', min: 5, max: 10 },
      { id: 'pricing', label: 'Pricing cases', kind: 'case', min: 0 },
      { id: 'strategy', label: 'Strategy cases', kind: 'case', min: 0 },
    ],
    approach: [
      ['Understand', 'Clarify the goal, context and key constraints'],
      ['Structure', 'Break down the problem with GTM levers or a prioritisation framework'],
      ['Analyse', 'Evaluate options using data, assumptions and frameworks'],
      ['Recommend', 'Make a clear, actionable recommendation'],
      ['Discuss', 'Explain trade-offs, risks and next steps'],
    ],
    outputs: ['Structured, logical answers', 'Clear recommendations with reasoning', 'Stronger business judgment and trade-off thinking'],
  },
  {
    n: 5,
    practice: ['guesstimate', 'behavioural'],
    slug: 'guesstimates-behavioural',
    title: 'Guesstimates, behavioural and favourite product',
    short: 'Guesstimates and behavioural',
    hours: 20,
    color: 'var(--w5)',
    summary: 'Tackle estimation questions, build your story bank and go deep on 2–3 products you know well.',
    means: [
      'Approach estimation questions with a structured mindset',
      'Prepare behavioural answers from real experiences using STAR',
      'Go deep on 2–3 products you know well',
      'Explain product decisions, metrics and impact clearly',
    ],
    todo: [
      'Practise 15–20 guesstimates across industries',
      'Build your behavioural story bank (15+ stories)',
      'Prepare deep dives on 2–3 favourite products',
      'Do mock interviews with peers or mentors',
      'Review feedback and refine your answers',
    ],
    trackers: [
      { id: 'guess', label: 'Guesstimates', kind: 'case', min: 15, max: 20 },
      { id: 'stories', label: 'Story bank', kind: 'story', min: 15, bank: true },
      { id: 'deepdives', label: 'Product deep dives', kind: 'deepdive', min: 2, max: 3, bank: true },
      { id: 'behav', label: 'Behavioural answers practised', kind: 'case', min: 0 },
      { id: 'peermocks', label: 'Peer mocks', kind: 'mock', min: 0 },
    ],
    approach: [
      ['Understand', 'Clarify what needs to be estimated or discussed'],
      ['Structure', 'Lay out a framework, top down or bottom up'],
      ['Estimate', 'Use logical assumptions and sanity checks'],
      ['Conclude', 'Arrive at a reasonable answer and discuss implications'],
      ['Communicate', 'Be clear, structured and confident'],
    ],
    outputs: ['Structured, logical answers', 'Strong, authentic behavioural stories', 'Clear product deep dives with insights and recommendations'],
  },
  {
    n: 6,
    practice: ['design', 'rca', 'strategy', 'guesstimate', 'behavioural'],
    slug: 'mocks-companies',
    title: 'Mocks and company preparation',
    short: 'Mocks and companies',
    hours: 10,
    color: 'var(--w6)',
    summary: 'Bring it all together, practise in a realistic setting and get company-ready.',
    means: [
      'Simulate real interview conditions',
      'Get comfortable with every format: product sense, design, RCA, metrics, behavioural',
      'Understand company-specific expectations',
      'Find your gaps and work on weak areas',
    ],
    todo: [
      'Take 4–6 full-length mocks',
      'Prepare company-wise: product, strategy, recent news, metrics',
      'Get feedback from peers, alumni or mentors',
      'Keep a repository of your best examples and frameworks',
      'Do timed practice and refine your communication',
    ],
    trackers: [
      { id: 'mocks', label: 'Full-length mocks', kind: 'mock', min: 4, max: 6 },
      { id: 'companies', label: 'Companies prepared', kind: 'company', min: 0, bank: true },
    ],
    approach: [
      ['Understand', 'Clarify the question and expectations'],
      ['Structure', 'Lay out your approach before diving in'],
      ['Solve', 'Walk through your thinking step by step'],
      ['Communicate', 'Be clear, concise and engage the interviewer'],
      ['Reflect', 'Take feedback and note areas to improve'],
    ],
    companyFocus: [
      ['Google', 'Product strategy, recent launches, key metrics, culture'],
      ['Microsoft', 'Cloud, AI, product portfolio, recent news'],
      ['Amazon', 'Leadership principles, growth levers, case studies'],
      ['Swiggy', 'Business model, unit economics, recent initiatives'],
      ['Netflix', 'User growth, content strategy, India opportunity'],
      ['Zomato (Eternal)', 'Food delivery dynamics, profitability, competition'],
    ],
    outputs: ['Comfortable with the end-to-end interview flow', 'Well prepared for your target companies', 'Clearer articulation and stronger confidence'],
  },
]

export const TOTAL_HOURS = WEEKS.reduce((s, w) => s + w.hours, 0)
export const trackerKey = (week, trackerId) => `w${week}.${trackerId}`
